version: '2'
volumes:
    node-red-data:
    node-red-test-data:
    influxdb-data:
services:
  influxdb:
    build: influxdb
    container_name: influxdb
    # privileged added so usb drive can be mounted.
    privileged: true
    volumes:
        # take care that the mount location "/mnt/influxdb" becomes overwritten
        # by the mount location specified in the influxdb Dockerfile.
        - 'influxdb-data:/mnt/influxdb'
    ports:
      # The API for InfluxDB is served on port 8086
      - "8082:8082"
      - "8086:8086"
      # UDP Port
      - "8089:8089"
    restart: always
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    build : telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    depends_on:
      - influxdb
    restart: always
    environment:
       - interval=60s
       - flush_interval=60s
  grafana:
    build: grafana
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: always
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  mqtt-test:
    image: panuwitp/mosquitto-arm
    ports:
      - "1884:1883"
  node-red:
    build: node-red
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
  node-red-test:
    build: node-red-test
    volumes:
       - 'node-red-test-data:/data'
    ports:
       - "1882:1880"
    depends_on:
        - mqtt-test
    restart: always
  nginx:
    build : nginx
    depends_on:
      - grafana
      - node-red
      - node-red-test
      - yoctopuce
    ports:
       - "80:80"
       - "443:443"
    restart: always
  yoctopuce:
    build: yoctopuce
    privileged: true
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "4445:4445"
    labels:
      io.balena.features.dbus: '1'
#    volumes:
#      - /dev/bus/usb:/dev/bus/usb
#      - /run/udev:/run/udev:ro
  sense-hat:
    build: sense-hat
    privileged: true
